#!/bin/bash

dbase="${1:-SFW_Households}"

# -r (raw) to omit tabular ouput
# -N (--skip-column-names)
declare -a cmd=(
    information_schema
    -r
    -N
    -e "SELECT COUNT(*) FROM SCHEMATA WHERE SCHEMA_NAME='$dbase'"
)

declare -i is_installed=$( mysql "${cmd[@]}" )

if [ $is_installed -eq 0 ]; then
    echo "Creating a new database"
    mysql -e "CREATE DATABASE IF NOT EXISTS $dbase"
    echo "Loading script files (and swallowing output)"
    declare swallow=$( mysql -f "${dbase}" < /usr/local/lib/SchemaServer/install/sys_procs.sql )
fi

echo Create links to custom files:
cp -fs ../custom/*.sql .
echo Rename so script with prerequisite procedures loads first.
mv Person_ISOTable.sql 1_Person_ISOTable.sql

mysql "$dbase" < tables.sql

declare -a scripts=( $( ls *.sql ) )
for script in "${scripts[@]}"; do
    if [[ ! "${script}" =~ tables*.sql ]]; then
       echo "Loading script file ${script}:"
       mysql "$dbase" < "${script}"
    fi
done
